title: Development of Visual Representations in Humans + Machines
description: DVRHM Workshop @ ICDL 2024

timezone: US/Eastern

navigation:
  Overview: "/"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Organizers: "/organizers"

markdown: kramdown

github:
  repository: https://github.com/ICDL-DVRHM/icdl-dvrhm.github.io

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
